{
  "url": "https://api.github.com/repos/facebook/react/issues/12228",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/12228/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/12228/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/12228/events",
  "html_url": "https://github.com/facebook/react/issues/12228",
  "id": 297270910,
  "node_id": "MDU6SXNzdWUyOTcyNzA5MTA=",
  "number": 12228,
  "title": "Issue with error boundaries and custom error types",
  "user": {
    "login": "bllfrnch",
    "id": 4458825,
    "node_id": "MDQ6VXNlcjQ0NTg4MjU=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/4458825?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/bllfrnch",
    "html_url": "https://github.com/bllfrnch",
    "followers_url": "https://api.github.com/users/bllfrnch/followers",
    "following_url": "https://api.github.com/users/bllfrnch/following{/other_user}",
    "gists_url": "https://api.github.com/users/bllfrnch/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/bllfrnch/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bllfrnch/subscriptions",
    "organizations_url": "https://api.github.com/users/bllfrnch/orgs",
    "repos_url": "https://api.github.com/users/bllfrnch/repos",
    "events_url": "https://api.github.com/users/bllfrnch/events{/privacy}",
    "received_events_url": "https://api.github.com/users/bllfrnch/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2018-02-14T22:38:35Z",
  "updated_at": "2018-02-14T23:45:24Z",
  "closed_at": "2018-02-14T23:45:24Z",
  "author_association": "NONE",
  "body": "I think I may have found a bug in React.\r\n\r\nI've defined a custom error type in a React application, which I'm throwing. I have an error boundary defined at the top of my application's component tree whose purpose is to catch uncaught errors and display an error page. The error boundary is catching the custom error, but isn't able to distinguish it from an error of type `Error`. Put simply, custom error types, created with the following syntax:\r\n\r\n```\r\nclass CustomError extends Error {}\r\n```\r\n\r\n... are, from the error boundary's perspective, simply errors of type `Error`, not `CustomError`. Further illustration – even though I'm explicitly throwing a `CustomError`, the error boundary's `componentDidCatch` method thinks its error argument is of type `Error`.\r\n\r\n```\r\ncomponentDidCatch(error, info) {\r\n  console.log(error instanceof Error); // true\r\n  console.log(error instanceof CustomError); // false\r\n  this.setState({\r\n    hasError: true,\r\n    error\r\n  });\r\n}\r\n```\r\n\r\nAm I crazy or is this a bug in React?\r\n\r\nThis issue is reproduced here: https://codepen.io/heywilly/pen/wyrKjz – the code is all documented, butin a nutshell, I've implemented an Application component that wraps its contents in an error boundary. A custom error is thrown from a subcomponent, and the custom typing gets lost somewhere along the way. That is, from the error boundary's perspective, the error that's thrown is of type `Error`, not the custom type defined in the application.\r\n\r\nAlso on StackOverflow: https://stackoverflow.com/questions/48777152/how-do-i-work-with-custom-error-types-in-react-error-boundaries/48792418\r\n\r\nThe expected behavior is that custom error types would be preserved as they crossed error boundaries.\r\n\r\nTested in React/ReactDOM 16.2.0, in Chrome 63.0.3239.132, MacOS 10.12.6.",
  "closed_by": {
    "login": "aweary",
    "id": 6886061,
    "node_id": "MDQ6VXNlcjY4ODYwNjE=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/6886061?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/aweary",
    "html_url": "https://github.com/aweary",
    "followers_url": "https://api.github.com/users/aweary/followers",
    "following_url": "https://api.github.com/users/aweary/following{/other_user}",
    "gists_url": "https://api.github.com/users/aweary/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/aweary/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/aweary/subscriptions",
    "organizations_url": "https://api.github.com/users/aweary/orgs",
    "repos_url": "https://api.github.com/users/aweary/repos",
    "events_url": "https://api.github.com/users/aweary/events{/privacy}",
    "received_events_url": "https://api.github.com/users/aweary/received_events",
    "type": "User",
    "site_admin": false
  }
}
