{
  "url": "https://api.github.com/repos/facebook/react/issues/12983",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/12983/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/12983/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/12983/events",
  "html_url": "https://github.com/facebook/react/issues/12983",
  "id": 329565918,
  "node_id": "MDU6SXNzdWUzMjk1NjU5MTg=",
  "number": 12983,
  "title": "Improve error message when got unexpected object in createElement",
  "user": {
    "login": "natew",
    "id": 12100,
    "node_id": "MDQ6VXNlcjEyMTAw",
    "avatar_url": "https://avatars0.githubusercontent.com/u/12100?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/natew",
    "html_url": "https://github.com/natew",
    "followers_url": "https://api.github.com/users/natew/followers",
    "following_url": "https://api.github.com/users/natew/following{/other_user}",
    "gists_url": "https://api.github.com/users/natew/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/natew/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/natew/subscriptions",
    "organizations_url": "https://api.github.com/users/natew/orgs",
    "repos_url": "https://api.github.com/users/natew/repos",
    "events_url": "https://api.github.com/users/natew/events{/privacy}",
    "received_events_url": "https://api.github.com/users/natew/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 4,
  "created_at": "2018-06-05T18:05:18Z",
  "updated_at": "2018-06-06T16:44:56Z",
  "closed_at": "2018-06-06T16:44:38Z",
  "author_association": "NONE",
  "body": "feature\r\n\r\n**What is the current behavior?**\r\n\r\nI've been running into an edge case where a view for some reason gets an object into createElement, triggering this error:\r\n\r\n```\r\nWarning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object\r\n```\r\n\r\nUnfortunately, I'm finding it really hard to debug. If I set \"break on errors\" for some reason it's not breaking. Perhaps this is some other bug with my setup (using chrome remote debugger + componentDidCatch), but I think this area could be improved a lot by outputting the object it got.\r\n\r\nIt's unfortunate there's no good way to log out an object in an error without doing hacky stringify things. But that would certainly have saved me a lot of time over the years using React, as I've run into this type of error a few times.\r\n\r\nIdeal would be just to log out a warning in dev mode, before the error throws, with something like:\r\n\r\n```js\r\nconsole.warn('React is about to throw an error due to an invalid property passed to React.createElement. Property is:', object)\r\n```\r\n",
  "closed_by": {
    "login": "aweary",
    "id": 6886061,
    "node_id": "MDQ6VXNlcjY4ODYwNjE=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/6886061?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/aweary",
    "html_url": "https://github.com/aweary",
    "followers_url": "https://api.github.com/users/aweary/followers",
    "following_url": "https://api.github.com/users/aweary/following{/other_user}",
    "gists_url": "https://api.github.com/users/aweary/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/aweary/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/aweary/subscriptions",
    "organizations_url": "https://api.github.com/users/aweary/orgs",
    "repos_url": "https://api.github.com/users/aweary/repos",
    "events_url": "https://api.github.com/users/aweary/events{/privacy}",
    "received_events_url": "https://api.github.com/users/aweary/received_events",
    "type": "User",
    "site_admin": false
  }
}
