{
  "url": "https://api.github.com/repos/facebook/react/issues/14331",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/14331/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/14331/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/14331/events",
  "html_url": "https://github.com/facebook/react/issues/14331",
  "id": 384536101,
  "node_id": "MDU6SXNzdWUzODQ1MzYxMDE=",
  "number": 14331,
  "title": "React 16.6.3 silently swallows an exception in `ReactDOMServer.renderToNodeStream()`",
  "user": {
    "login": "asyncmax",
    "id": 8050963,
    "node_id": "MDQ6VXNlcjgwNTA5NjM=",
    "avatar_url": "https://avatars3.githubusercontent.com/u/8050963?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/asyncmax",
    "html_url": "https://github.com/asyncmax",
    "followers_url": "https://api.github.com/users/asyncmax/followers",
    "following_url": "https://api.github.com/users/asyncmax/following{/other_user}",
    "gists_url": "https://api.github.com/users/asyncmax/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/asyncmax/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/asyncmax/subscriptions",
    "organizations_url": "https://api.github.com/users/asyncmax/orgs",
    "repos_url": "https://api.github.com/users/asyncmax/repos",
    "events_url": "https://api.github.com/users/asyncmax/events{/privacy}",
    "received_events_url": "https://api.github.com/users/asyncmax/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 40929151,
      "node_id": "MDU6TGFiZWw0MDkyOTE1MQ==",
      "url": "https://api.github.com/repos/facebook/react/labels/Type:%20Bug",
      "name": "Type: Bug",
      "color": "b60205",
      "default": false
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 3,
  "created_at": "2018-11-26T22:21:48Z",
  "updated_at": "2018-11-27T13:09:13Z",
  "closed_at": "2018-11-27T13:01:00Z",
  "author_association": "NONE",
  "body": "This is reproducible with the following snippet:\r\n\r\n```\r\n\"use strict\";\r\n\r\nconst React = require(\"react\");\r\nconst ReactDOMServer = require(\"react-dom/server\");\r\n\r\nfunction Hello() {\r\n  throw new Error(\"foo\");\r\n  return React.createElement(\"div\", null, \"Hello, world!\");\r\n}\r\n\r\nconst stream = ReactDOMServer.renderToNodeStream(React.createElement(Hello));\r\n\r\nstream.on(\"data\", chunk => {\r\n  console.log(chunk.toString());\r\n});\r\n\r\nstream.on(\"end\", () => {\r\n  console.log(\"-- done --\");\r\n});\r\n\r\nstream.on(\"error\", err => {\r\n  console.error(err);\r\n});\r\n```\r\n\r\nReact 16.6.1 emits an `error` event as expected, but React 16.6.3 silently swallows an exception, leaving the stream in a broken state in which it never ends.\r\n\r\nThis problem appears to be caused by this modification in `ReactDOMNodeStreamRenderer.js`:\r\n\r\nhttps://github.com/facebook/react/commit/b545546ccbe056e35c6be9c938561df643cc3950#diff-1090c7a359d6dc602b62ac38b66697b3L25\r\n\r\nHere, `stream.destroy` gets called with an exception object but the actual handler `stream._destroy` doesn't use it anywhere which results in ignoring the exception.\r\n",
  "closed_by": {
    "login": "gaearon",
    "id": 810438,
    "node_id": "MDQ6VXNlcjgxMDQzOA==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/810438?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gaearon",
    "html_url": "https://github.com/gaearon",
    "followers_url": "https://api.github.com/users/gaearon/followers",
    "following_url": "https://api.github.com/users/gaearon/following{/other_user}",
    "gists_url": "https://api.github.com/users/gaearon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gaearon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gaearon/subscriptions",
    "organizations_url": "https://api.github.com/users/gaearon/orgs",
    "repos_url": "https://api.github.com/users/gaearon/repos",
    "events_url": "https://api.github.com/users/gaearon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gaearon/received_events",
    "type": "User",
    "site_admin": false
  }
}
