{
  "url": "https://api.github.com/repos/facebook/react/issues/15635",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/15635/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/15635/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/15635/events",
  "html_url": "https://github.com/facebook/react/issues/15635",
  "id": 443436192,
  "node_id": "MDU6SXNzdWU0NDM0MzYxOTI=",
  "number": 15635,
  "title": "Document an unmentioned reason for hook errors.",
  "user": {
    "login": "bebbi",
    "id": 2752391,
    "node_id": "MDQ6VXNlcjI3NTIzOTE=",
    "avatar_url": "https://avatars0.githubusercontent.com/u/2752391?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/bebbi",
    "html_url": "https://github.com/bebbi",
    "followers_url": "https://api.github.com/users/bebbi/followers",
    "following_url": "https://api.github.com/users/bebbi/following{/other_user}",
    "gists_url": "https://api.github.com/users/bebbi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/bebbi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bebbi/subscriptions",
    "organizations_url": "https://api.github.com/users/bebbi/orgs",
    "repos_url": "https://api.github.com/users/bebbi/repos",
    "events_url": "https://api.github.com/users/bebbi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/bebbi/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2019-05-13T14:37:58Z",
  "updated_at": "2019-05-14T09:00:27Z",
  "closed_at": "2019-05-14T09:00:26Z",
  "author_association": "NONE",
  "body": "This [page](https://reactjs.org/warnings/invalid-hook-call-warning.html) and #13991 document the `Hooks can only be called inside the body of a function component.` error.\r\n\r\nI encountered the same error on a completely unrelated bug: I forgot to *call* the hook:\r\n\r\n```\r\nconst MyComp = () => {\r\n  const myVar = useHook  // missing the `()`\r\n  return <Something />\r\n}\r\n```\r\n\r\nWhile that's a silly omission, it's maybe worth documenting to make the error more concise. Feel free to close either way.",
  "closed_by": {
    "login": "threepointone",
    "id": 18808,
    "node_id": "MDQ6VXNlcjE4ODA4",
    "avatar_url": "https://avatars2.githubusercontent.com/u/18808?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/threepointone",
    "html_url": "https://github.com/threepointone",
    "followers_url": "https://api.github.com/users/threepointone/followers",
    "following_url": "https://api.github.com/users/threepointone/following{/other_user}",
    "gists_url": "https://api.github.com/users/threepointone/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/threepointone/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/threepointone/subscriptions",
    "organizations_url": "https://api.github.com/users/threepointone/orgs",
    "repos_url": "https://api.github.com/users/threepointone/repos",
    "events_url": "https://api.github.com/users/threepointone/events{/privacy}",
    "received_events_url": "https://api.github.com/users/threepointone/received_events",
    "type": "User",
    "site_admin": false
  }
}
