{
  "url": "https://api.github.com/repos/facebook/react/issues/6382",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/6382/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/6382/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/6382/events",
  "html_url": "https://github.com/facebook/react/issues/6382",
  "id": 144715747,
  "node_id": "MDU6SXNzdWUxNDQ3MTU3NDc=",
  "number": 6382,
  "title": "server is running and I include the export line its not throwing an error",
  "user": {
    "login": "js08",
    "id": 1699943,
    "node_id": "MDQ6VXNlcjE2OTk5NDM=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/1699943?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/js08",
    "html_url": "https://github.com/js08",
    "followers_url": "https://api.github.com/users/js08/followers",
    "following_url": "https://api.github.com/users/js08/following{/other_user}",
    "gists_url": "https://api.github.com/users/js08/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/js08/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/js08/subscriptions",
    "organizations_url": "https://api.github.com/users/js08/orgs",
    "repos_url": "https://api.github.com/users/js08/repos",
    "events_url": "https://api.github.com/users/js08/events{/privacy}",
    "received_events_url": "https://api.github.com/users/js08/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 5,
  "created_at": "2016-03-30T20:47:28Z",
  "updated_at": "2016-03-30T21:34:24Z",
  "closed_at": "2016-03-30T20:51:21Z",
  "author_association": "NONE",
  "body": "- I am facing a weird error\n- when the server is running and I include the export line its not throwing an error and able to see the application...even it shows webpack is valid\n  export { SportsTopPortion  };\n- but after including this line and start the server again I am facing the error\n  Error: Invariant Violation:\n- i am using webpack,node and react\n- since I am using webpack for build I am thinking the error will be due to webpack\n- checked React code for errors there is no problem in syntax.\n- can you tell me how to fix it..\n- the reason I am using export is to write unit test case\n- whole code and test code can be seen in gist below\n- I am debugging for past four days not able to find out\n",
  "closed_by": {
    "login": "zpao",
    "id": 8445,
    "node_id": "MDQ6VXNlcjg0NDU=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/8445?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/zpao",
    "html_url": "https://github.com/zpao",
    "followers_url": "https://api.github.com/users/zpao/followers",
    "following_url": "https://api.github.com/users/zpao/following{/other_user}",
    "gists_url": "https://api.github.com/users/zpao/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/zpao/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/zpao/subscriptions",
    "organizations_url": "https://api.github.com/users/zpao/orgs",
    "repos_url": "https://api.github.com/users/zpao/repos",
    "events_url": "https://api.github.com/users/zpao/events{/privacy}",
    "received_events_url": "https://api.github.com/users/zpao/received_events",
    "type": "User",
    "site_admin": false
  }
}
