{
  "url": "https://api.github.com/repos/facebook/react/issues/7927",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/7927/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/7927/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/7927/events",
  "html_url": "https://github.com/facebook/react/issues/7927",
  "id": 181978202,
  "node_id": "MDU6SXNzdWUxODE5NzgyMDI=",
  "number": 7927,
  "title": "Changing state too quickly cause error with shallow render",
  "user": {
    "login": "Sawtaytoes",
    "id": 3948069,
    "node_id": "MDQ6VXNlcjM5NDgwNjk=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/3948069?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Sawtaytoes",
    "html_url": "https://github.com/Sawtaytoes",
    "followers_url": "https://api.github.com/users/Sawtaytoes/followers",
    "following_url": "https://api.github.com/users/Sawtaytoes/following{/other_user}",
    "gists_url": "https://api.github.com/users/Sawtaytoes/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Sawtaytoes/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Sawtaytoes/subscriptions",
    "organizations_url": "https://api.github.com/users/Sawtaytoes/orgs",
    "repos_url": "https://api.github.com/users/Sawtaytoes/repos",
    "events_url": "https://api.github.com/users/Sawtaytoes/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Sawtaytoes/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 2,
  "created_at": "2016-10-10T10:07:15Z",
  "updated_at": "2016-11-16T11:08:59Z",
  "closed_at": "2016-10-27T09:31:10Z",
  "author_association": "NONE",
  "body": "**Do you want to request a _feature_ or report a _bug_?**\nReport a bug\n\n**What is the current behavior?**\nRunning `ReactTestUtils.createRenderer().render()` causes react to throw an exception:\n\n```\nWarning: Exception thrown by hook while handling onSetChildren: Invariant Violation: Expected onBeforeMountComponent() parent and onSetChildren() to be consistent (3 has parents 0 and 2).\nInvariant Violation: Expected onBeforeMountComponent() parent and onSetChildren() to be consistent (3 has parents 0 and 2).\n```\n\nI have the same issue when using both `Component` and `PureComponent`.\nI do _not_ see the error when using `ReactTestUtils.renderToDocument()`.\n\n**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**\nCould not figure out how to use `ReactTestUtils` in that JSFiddle example even though react-with-addons is loaded.\n\nHere's the code I used in my project to reproduce it:\n\n``` jsx\nimport React, { Component, PureComponent } from 'react'\nimport { render } from 'react-dom'\nimport ReactTestUtils from 'react-addons-test-utils'\n\nclass Root extends Component {\n    componentWillMount() {\n        this.testBreak()\n        setTimeout(this.testBreak.bind(this), 10)\n    }\n\n    testBreak() {\n        var i = 0, l = 50\n        while(i <= l) {\n            this.setState({ test: `this will break testing ${++i}` })\n        }\n    }\n\n    render() {\n        return (\n            <div>\n                {/* You need more than one nested element for this to break */}\n                <div>First div</div>\n                <div>Second div</div>\n            </div>\n        )\n    }\n}\n\nrender(\n    <Root />\n, document.getElementById('root'))\n\nclass TestReactElement extends PureComponent {\n    render() { return (\n        <div>{this.props.name}</div>\n    )}\n}\n\nconst testRender = (name) => {\n    let renderer = ReactTestUtils.createRenderer()\n    renderer.render(<TestReactElement name={name} />)\n}\n\ntestRender('Test 1')\ntestRender('Test 2')\ntestRender('Test 3')\n```\n\nIt works fine so long as I run `testRender()` once. As soon as it's run 2 or more times, the error pops up.\n\nIn my project, TAP output is being listened to from a `console.log` wrapper and `state` is being updated when a new one comes in. So while my reproducible example is contrived, it's real-world bug when running tests in my project.\n\n**What is the expected behavior?**\nThe expected behavior is that no error occurs in the console when running multiple shallow test renders while at the same time React is updating the state of an element rendered to the DOM.\n\n**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**\n`15.3.0` and `15.3.2`. Windows 10 64-bit v1607 (and updates up to October 10th, 2016). I've not tried this in previous versions of React. Verified it displays the error in Chrome `54.0.2840.50 beta-m (64-bit)` and Firefox `50.0b5`.\n",
  "closed_by": {
    "login": "gaearon",
    "id": 810438,
    "node_id": "MDQ6VXNlcjgxMDQzOA==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/810438?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gaearon",
    "html_url": "https://github.com/gaearon",
    "followers_url": "https://api.github.com/users/gaearon/followers",
    "following_url": "https://api.github.com/users/gaearon/following{/other_user}",
    "gists_url": "https://api.github.com/users/gaearon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gaearon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gaearon/subscriptions",
    "organizations_url": "https://api.github.com/users/gaearon/orgs",
    "repos_url": "https://api.github.com/users/gaearon/repos",
    "events_url": "https://api.github.com/users/gaearon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gaearon/received_events",
    "type": "User",
    "site_admin": false
  }
}
