{
  "url": "https://api.github.com/repos/facebook/react/issues/9571",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/9571/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/9571/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/9571/events",
  "html_url": "https://github.com/facebook/react/issues/9571",
  "id": 225489030,
  "node_id": "MDU6SXNzdWUyMjU0ODkwMzA=",
  "number": 9571,
  "title": "\"Error boundary\" text is not clear",
  "user": {
    "login": "darknoon",
    "id": 355540,
    "node_id": "MDQ6VXNlcjM1NTU0MA==",
    "avatar_url": "https://avatars2.githubusercontent.com/u/355540?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/darknoon",
    "html_url": "https://github.com/darknoon",
    "followers_url": "https://api.github.com/users/darknoon/followers",
    "following_url": "https://api.github.com/users/darknoon/following{/other_user}",
    "gists_url": "https://api.github.com/users/darknoon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/darknoon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/darknoon/subscriptions",
    "organizations_url": "https://api.github.com/users/darknoon/orgs",
    "repos_url": "https://api.github.com/users/darknoon/repos",
    "events_url": "https://api.github.com/users/darknoon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/darknoon/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 14,
  "created_at": "2017-05-01T18:18:11Z",
  "updated_at": "2017-09-28T21:40:20Z",
  "closed_at": "2017-08-02T10:09:45Z",
  "author_association": "NONE",
  "body": "**Error text enhancement request**\r\n\r\n**What is the current behavior?**\r\n\r\nWhen an exception is thrown, something like this is printed:\r\n\r\n```\r\nReact caught an error thrown by <REDACTED>. You should fix this error in your code. Consider adding an error boundary to your tree to customize error handling behavior.\r\n\r\nTypeError: undefined is not an object (evaluating 'flags.<REDACTED>')\r\n\r\nThe error is located at: \r\n   <REDACTED>\r\n    in Editor (created by Connect(Editor))\r\n    in Connect(Editor) (created by RouterContext)\r\n    in div (created by App)\r\n    in App (created by Connect(App))\r\n    in Connect(App) (created by RouterContext)\r\n    in RouterContext (created by Router)\r\n    in Router\r\n    in Provider\r\n\r\nThe error was thrown at: \r\n```\r\n\r\nIt's not clear what an \"error boundary\" is. It would be great to link to a docs page that describes what this is and how to do it.\r\n\r\nI googled \"react error boundary\" and ended up with no clear answers in the top few hits.\r\nhttps://www.google.com/search?client=safari&rls=en&q=react+error+boundary&ie=UTF-8&oe=UTF-8",
  "closed_by": {
    "login": "gaearon",
    "id": 810438,
    "node_id": "MDQ6VXNlcjgxMDQzOA==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/810438?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gaearon",
    "html_url": "https://github.com/gaearon",
    "followers_url": "https://api.github.com/users/gaearon/followers",
    "following_url": "https://api.github.com/users/gaearon/following{/other_user}",
    "gists_url": "https://api.github.com/users/gaearon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gaearon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gaearon/subscriptions",
    "organizations_url": "https://api.github.com/users/gaearon/orgs",
    "repos_url": "https://api.github.com/users/gaearon/repos",
    "events_url": "https://api.github.com/users/gaearon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gaearon/received_events",
    "type": "User",
    "site_admin": false
  }
}
